FROM python:3.10-slim

COPY requirements.txt /opt/dagster/app/
WORKDIR /opt/dagster/app

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Add repository code into docker
COPY ./dags/ /opt/dagster/app/

# Run dagster gRPC server on port 4000
EXPOSE 4000
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "app.py"]
